[package]
name = "rspy"
version = "0.1.0"
description = "Python-like interface"
repository = "https://github.com/seijinrosen/rspy"
readme = "README.md"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
